import './globals.css';
import type { Metadata } from 'next';
import Audio from '@/components/Audio';
import Splash from '@/components/section/Splash';
import { DM_Sans, Newsreader } from 'next/font/google';

const dmSans = DM_Sans({
    subsets: ['latin'],
});

const newsReader = Newsreader({
    subsets: ['latin'],
    variable: '--newsreader',
});

export const metadata: Metadata = {
    title: 'Andry & Meylani',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${dmSans.className} ${newsReader.variable} bg-amber-50 text-zinc-800 antialiased`}>
                <Audio />
                <Splash />
                {children}
            </body>
        </html>
    );
}
